variable "cinemas_org" {
  default = {
    enable      = true
    description = "Cinemas bootstrap - Organization generated by terraform harness provider"
    projects = {
      "Movie Service" = {
        enable      = true
        description = "Project generated by terraform harness provider"
      }
      "Payments Service" = {
        enable      = true
        description = "Project generated by terraform harness provider"
      }
    }
  }
}

locals {
  cinemas_org_delegates = {
    k8s = {
      cinemas-gke-tf = {
        enable                 = true
        description            = "Delegate deployed and generated by terraform harness provider"
        size                   = "SMALL"
        tags                   = ["gcp-environment"]
        clusterPermissionType  = "CLUSTER_ADMIN"
        customClusterNamespace = "harness-delegate-ng"
        org_id                 = module.bootstrap_cinemas_org.organization["cinemas-org"].org_id
      }
    }
  }

  cinemas_org_connectors = {
    github = {
      cinemas-dev-movie = {
        enable          = true
        description     = "Github Cinemas - Connector generated by terraform harness provider"
        connection_type = "Account"
        url             = "https://github.com/Crizstian"
        validation_repo = "harness-as-code"
        org_id          = module.bootstrap_cinemas_org.project["Movie Service"].org_id
        project_id      = module.bootstrap_cinemas_org.project["Movie Service"].identifier
        credentials = {
          http = {
            username  = "crizstian"
            token_ref = var.harness_connectors_crizstian_github_token
          }
        }
      }
      # cinemas-dev-payment = {
      #   enable          = true
      #   description     = "Github Cinemas - Connector generated by terraform harness provider"
      #   connection_type = "Account"
      #   url             = "https://github.com/Crizstian"
      #   validation_repo = "harness-as-code"
      #   org_id          = module.bootstrap_cinemas_org.project["Payment Service"].org_id
      #   project_id      = module.bootstrap_cinemas_org.project["Payment Service"].identifier
      #   credentials = {
      #     http = {
      #       username  = "crizstian"
      #       token_ref = var.harness_connectors_crizstian_github_token
      #     }
      #   }
      # }
    }
    # docker = {
    #   cinemas-dev = {
    #     enable      = false
    #     description = "Connector generated by terraform harness provider"
    #     tags        = ["local:environment"]
    #     # delegate_selectors = ["local-environment"]
    #     org_id = ""
    #     type   = "DockerHub"
    #     url    = "https://registry.hub.docker.com/v1/"
    #     credentials = {
    #       username = "crizstian"
    #       # password_ref = var.harness_connectors_crizstian_docker_token
    #     }
    #   }
    # }
  }
}
