variable "harness_platform_account_id" {
  sensitive = true
}
variable "harness_platform_api_key" {
  sensitive = true
}

variable "harness_platform_projects" {
  default = {
    cristian-terraform-org = {
      enable      = true
      description = "Organization generated by terraform harness provider"
      projects = {
        "Movie Service" = {
          enable      = true
          description = "Project generated by terraform harness provider"
        }
        "Payments Service" = {
          enable      = true
          description = "Project generated by terraform harness provider"
        }
      }
    }
  }
}
